- aiosmtpd/docs/NEWS.rst
- aiosmtpd/smtp.py
> Close the transport on SMTP QUIT.

- aiosmtpd/smtp.py
- aiosmtpd/tests/test_smtp.py
Which can use for set custom hostname for smtpd and avoid blocking on call socket.getfqdn().
> Added new parameter hostname for SMTP

- .gitignore
- aiosmtpd/docs/NEWS.rst
- aiosmtpd/smtp.py
- aiosmtpd/tests/test_smtp.py
- tox.ini
* The SMTP server connection identifier can be changed by setting the
`__ident__` attribute on the `SMTP` instance.  (Closes #20)
* Ignore some git artifacts.
* Add a -diffcov generated tox environment for ensuring that any
pull requests tests the new code 100%.
> Closes #20

- aiosmtpd/main.py
- aiosmtpd/smtp.py
- tox.ini
flake8 `hang-closing = True` to be exact.
> Enforce a stricter coding style

- aiosmtpd/smtp.py
- aiosmtpd/tests/test_smtp.py
Added error handling to catch exceptions in handler, and do not crush on unexpected errors (for example during message processing)
> Error handling

- aiosmtpd/smtp.py
This attributes not used anymore.
> remove obsolete attributes from init

- aiosmtpd/handlers.py
- aiosmtpd/smtp.py
- aiosmtpd/tests/test_smtp.py
During #39  and #45 I missed this review based commit.
> Rename envelope data to content field

- aiosmtpd/docs/NEWS.rst
- aiosmtpd/docs/smtp.rst
- aiosmtpd/smtp.py
- aiosmtpd/tests/test_starttls.py
This builds on, but changes #53 and should replace that branch.
> Rename handle_tls_handshake() to handle_STARTTLS

- aiosmtpd/handlers.py
- aiosmtpd/tests/test_handlers.py
Most of this branch comes from #74 with additional coverage/test refactoring and some coding style fixes by me.
> Proxy can decode bytes or not

- aiosmtpd/docs/NEWS.rst
- aiosmtpd/smtp.py
> 1.0 beta 1

- aiosmtpd/controller.py
This change comes from discussions on
https://github.com/python/cpython/pull/1492
> We don't need a socketpair to stop the subthread

- aiosmtpd/docs/NEWS.rst
- aiosmtpd/smtp.py
- aiosmtpd/tests/test_smtp.py
This is #106 with a NEWS file entry and a few minor cleanups.
Do not squash commits!
> Minor cosmetic cleanups from #106

- aiosmtpd/smtp.py
- aiosmtpd/tests/test_smtp.py
See http://bugs.python.org/issue21783 for initial report and discussion
of this issue.
> Fix #78 by removing error on duplicate greetings.

- aiosmtpd/docs/NEWS.rst
- aiosmtpd/main.py
- aiosmtpd/tests/test_main.py
> Add --version / -v to the CLI

- aiosmtpd/smtp.py
- aiosmtpd/tests/test_smtp.py
Adds a minimal test case based on #110 and fixes #110.
> Handle EOF from client before QUIT

- README.rst
- aiosmtpd/docs/NEWS.rst
- aiosmtpd/docs/manpage.rst
- aiosmtpd/main.py
> Add a manpage

- aiosmtpd/smtp.py
- aiosmtpd/tests/test_main.py
- aiosmtpd/tests/test_smtps.py
> Clean tests

- .appveyor.yml
- aiosmtpd/smtp.py
- aiosmtpd/tests/test_main.py
> Hacking on PR121

- aiosmtpd/docs/NEWS.rst
- aiosmtpd/docs/smtp.rst
- aiosmtpd/smtp.py
- aiosmtpd/tests/test_smtp.py
Addresses https://github.com/aio-libs/aiosmtpd/issues/131
>  Add customizable ident field to SMTP class init

- .travis.yml
- aiosmtpd/controller.py
- aiosmtpd/docs/controller.rst
- examples/server.py
Also updates example to use dual-stack binding. Fixes #140.
> Add docstring to Controller, explaining dual-stack binding.

- aiosmtpd/docs/NEWS.rst
I've learned that I'll need to pester PR authors for this :)
> Add NEWS updates for release

- .travis.yml
Based on https://github.com/aio-libs/aiosmtpd/pull/151#issuecomment-447775725 - in theory this build should provide the coverage results from codecov...
> Use codecov

- .coveragerc
- .gitignore
- .travis.yml
- README.rst
- aiosmtpd/controller.py
- aiosmtpd/handlers.py
- aiosmtpd/main.py
- aiosmtpd/smtp.py
- aiosmtpd/tests/test_main.py
- aiosmtpd/tests/test_server.py
- aiosmtpd/tests/test_smtp.py
- setup.py
- tox.ini
- unittest.cfg
These are cherry-picked commits from PR #192 _only_ related to tox + unittest + coverage.py
In summary, major things implemented in this PR:
* Fixes tox to run well on three platforms: Windows, WSL, and Ubuntu
* Fixes a lot of niggling "qa" fails _which had been happening in_ master _for some time but no one ever tried to fix (apparently)_
* Adds support for Python 3.8, Python 3.9, and PyPy3
* Workaround due to Python 3.8 error messages "bleeding through" [1]
* Optimize Travis config
* Update `README.rst` to explain more about how we do tox
Since all but one (marked "[1]" above) of the changes are picked directly from PR #192 , merging this should not block #192 from being merged.
None.
This only makes QA life easier.
None.
> Tox Fixing (cherry-picked and hand-picked from 192)

- LICENSE
- README.rst
- aiosmtpd/docs/NEWS.rst
Add **Apache License v2.0** as discussed in #170 
And a selection of badges so we look similar to [aiohttp](https://github.com/aio-libs/aiohttp) now! 😁
None.
Resolves #170
> License & Badges

- aiosmtpd/smtp.py
A version bump for uploading to PyPI
> Release 1.2.2

- MANIFEST.in
MANIFEST.in:
Simplify the file by using graft to add the aiosmtpd package [1].
Prune .tox and .venv so that they do not end up in an sdist tarball.
[1] https://docs.python.org/3/distutils/commandref.html
Fixes #203
see above
see above
see above
* name it `<issue_id>.<type>` (e.g. `588.bugfix`)
* if you don't have an `issue_id` change it to the pr id after creating the PR
* ensure type is one of the following:
* `.feature`: Signifying a new feature.
* `.bugfix`: Signifying a bug fix.
* `.doc`: Signifying a documentation improvement.
* `.removal`: Signifying a deprecation or removal of public API.
* `.misc`: A ticket has been closed, but it is not of interest to users.
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue with non-ascii contents in …
> Simplify MANIFEST.in

- .travis.yml
Enable Python version 3.9 in the CI.
No
> Test Python 3.9 with Travis CI

- README.rst
- _static/aiosmtpd.css
- _static/css/aiosmtpd.css
- aiosmtpd/docs/controller.rst
- aiosmtpd/docs/index.rst
- aiosmtpd/docs/ref-controller.rst
- aiosmtpd/docs/ref-smtp.rst
- aiosmtpd/docs/smtp.rst
- aiosmtpd/smtp.py
- conf.py
Improve structure & visual of documentation, plus removing Sphinx features not supported by GitHub.
To see how README looks like after changes, visit my branch: https://github.com/pepoluan/aiosmtpd/tree/better-github-readme
To see how the docs look like after changes, run `tox -e docs` and open `build\sphinx\html\aiosmtpd\docs\index.html`
None, this is docs only.
None
> Better Documentation & README

- DESCRIPTION.rst
- README.rst
Update the collection of badges/shields in `README.rst` and `DESCRIPTION.rst` (PyPI package long-desc)
None.
Kind of related to #197 and #227
> Add New Badge + reorder

- aiosmtpd/controller.py
- aiosmtpd/handlers.py
- aiosmtpd/proxy_protocol.py
- aiosmtpd/smtp.py
- aiosmtpd/tests/test_handlers.py
- aiosmtpd/tests/test_proxyprotocol.py
- aiosmtpd/tests/test_server.py
- aiosmtpd/tests/test_smtp.py
- housekeep.py
- release.py
- setup.cfg
Fixes the QA job by ignoring or fixing new Flake8 checks added by various plugins.
No.
Related to #277 
> fix: Fix the QA job by skipping some checks and fix others.

- .gitignore
- MANIFEST.in
- aiosmtpd/qa/test_0packaging.py
- tox.ini
What it says on the tin.
Was working on reviewing #311 and the qa tools complained, loudly, about my swap files :joy:
> Add vim swap files to gitignore

- .gitignore
- DESCRIPTION.rst
- MANIFEST.in
- README.rst
- aiosmtpd/__init__.py
- aiosmtpd/docs/NEWS.rst
- aiosmtpd/docs/controller.rst
- setup.cfg
- tox.ini
Mostly, version bumping.
Also some fixings for tox. Notably, taking out pytype.
None
None directly
> Bump to 1.4.3

- aiosmtpd/smtp.py
After created an SSL context to support STARTTLS command, tried to run command:
`openssl s_client -starttls smtp -crlf  -connect localhost:8025`
it raises:
`
Traceback (most recent call last):
File "/.../lib/python3.10/site-packages/aiosmtpd/smtp.py", line 741, in _handle_client
await method(arg)
File "/.../lib/python3.10/site-packages/aiosmtpd/smtp.py", line 901, in smtp_STARTTLS
self._original_transport._protocol = self._tls_protocol
AttributeError: 'uvloop.loop.TCPTransport' object has no attribute '_protocol'
`
- **uvloop version**: 0.16.0
- **python version**: 3.10
- **platform**: Linux Mint 20.2
Since the minimal python version is 3.6 and `set_protocol()` was added in python 3.5, the above method was used to fix the error.
No user-visible changes made.
* Add under the …
> Fixed STARTTLS with uvloop

- .github/workflows/unit-testing-and-coverage.yml
- README.rst
Some improvements in GHCI
None
None
> GHCI Improvements 2

- DESCRIPTION.rst
- README.rst
Fix the defunct LGTM badge, replace with PythonImplementation badge.
And some stats for PyPI Description.
Maybe make them more in awe?
None
> Minor readme fixes

- aiosmtpd/__init__.py
- aiosmtpd/docs/NEWS.rst
- release.py
Bump version to 1.4.4a0 to keep 1.4.3 'safe' from tainting :-)
None, this is not released to user.
None
> Bump version to 1.4.4a0
