aiosmtpd/smtp.py

How to reproduce:
Run smtpd server with code:
```python
import asyncio
import logging
from aiosmtpd.handlers import Sink
from aiosmtpd.controller import Controller
async def amain(loop):
cont = Controller(Sink(), hostname='::0', port=8025)
cont.start()
if __name__ == '__main__':
logging.basicConfig(level=logging.DEBUG)
loop = asyncio.get_event_loop()
loop.create_task(amain(loop=loop))
loop.run_forever()
```
and try send mail:
```python
from smtplib import SMTP
client = SMTP(
'127.0.0.1', 8025
)
client.sendmail(
'from@test',
['to@test'],
"""\
From: from@test
To: to@test
Subject: A test
Test mail
"""
)
```
You will see a lot of errors in server output log:
```
WARNING:asyncio:socket.send() raised exception.
DEBUG:mail.log:b'500 Error: bad syntax\r\n'
INFO:mail.log:Data: '' …
```

Correct handle end of the communication and client disconnect

---

aiosmtpd/docs/NEWS.rst
aiosmtpd/docs/controller.rst
aiosmtpd/handlers.py
aiosmtpd/tests/test_handlers.py

Older libraries such as lazr.smtpttest used `X-RcptTo` (singular).  Change the `Message` handler header to match.

X-RcptTos header -> X-RcptTo

---

aiosmtpd/controller.py
aiosmtpd/docs/NEWS.rst
aiosmtpd/smtp.py

I'm in the process of converting the GNU Mailman 3 trunk from lazr.smtptest to aiosmtpd.  Of course, it's *much* nicer to use asyncio than asynchat/asyncore-based smtpd.py, but there are a few hooks I found I needed to make it just that much more comfortable.  These allow subclasses to not have to reimplement entire methods just to add a little bit of functionality.  
- `SMTP.ehlo_hook()` is called just before the final, non-continuing 250
response to allow subclasses to add additional EHLO sub-responses.
- `SMTP.rset_hook()` is called just before the final 250 command to allow
subclasses to provide additional `RSET` functionality.
- `Controller.make_socket()` allows subclasses to customize the creation of
the socket before binding.

Add a few useful hooks to make subclassing easier.

---

setup.py
tox.ini

atpublic no longer has that flake8 plugin, so installing aiosmtpd 0.3 fails.

Use flufl.testing's flake8 plugin.

---

aiosmtpd/smtp.py
aiosmtpd/tests/test_starttls.py

@athoune is right, in newest python 3.4 is not enough to import SSL modules, also need to check that MemoryBIO is available.

Fix ssl detection

---

aiosmtpd/handlers.py
aiosmtpd/smtp.py
aiosmtpd/tests/test_handlers.py
aiosmtpd/tests/test_smtp.py

Here is two fixes with DATA method.
1. Respect original line endings. That`s not obvious, as RFC says that line endings must be only CR LF but on practice there can be anything, and better to keep it "as is" to not confuse on email debug. Anyway it is good idea to have ability to get real original data of email. Also, email.parse_message works fine with any line endings, so there is no real need to fix them.
2. Size limit had a side effect. If limit is reached, all other lines of DATA will fallback to root handler and will be handled as syntax errors. Better to read them, but ignore.
Also I removed using of instance properties for local variables. Seems that it is migrated from state-machine implementation.

Refactor DATA method

---

aiosmtpd/tests/test_smtp.py
tox.ini

Also, don't be so verbose when coverage testing.

Suppress possible output to the console during the test

---

aiosmtpd/controller.py
aiosmtpd/docs/controller.rst
aiosmtpd/tests/test_server.py

Simple fix for https://github.com/aio-libs/aiosmtpd/issues/35
~~Currently the timeout is opt-in, you might want to consider adding a default value to it if it works out well.~~

Add socket error handling to Controller thread

---

aiosmtpd/smtp.py
aiosmtpd/tests/test_smtp.py

Hey! I watchng on you )
RFC 5321 4.1.1.4.  DATA (DATA)
The mail data are terminated by a line containing only a period, that
is, the character sequence "<CRLF>.<CRLF>", where the first <CRLF> is
actually the terminator of the previous line
So, empty email will raise IndexError exception with your last changes.
I`m lazy ass to not adding a test for that.

Data command fix

---

aiosmtpd/controller.py
aiosmtpd/main.py
aiosmtpd/tests/test_main.py
aiosmtpd/tests/test_smtp.py

Removed socket opening code to rely on asyncio more complicated solution.
+ setuid test skip if it is unavailable (on Windows)
+ Windows compatible asyncio-way socket pair creation
After this tests are passed on Windows with python 3.4/3.5.

Crossplatform  Windows compatibility

---

aiosmtpd/docs/NEWS.rst
aiosmtpd/docs/smtp.rst
aiosmtpd/handlers.py
aiosmtpd/smtp.py
aiosmtpd/tests/test_handlers.py
aiosmtpd/tests/test_smtp.py

As an alternative to #41 here's my rough idea for a generic hook mechanism.  This is a WIP with the intention of sparking discussion.  If this is acceptable, it still needs fleshing out (more hooks), NEWS, and documentation.
I tried to make this even more generic by building the calling of handler hooks into `_handle_client()` but that had several problems.  The most complicated is that it would not allow hooks to set different statuses without changing the API of existing `SMTP.smtp_*()` methods.  Well, with avoiding exceptions for error statuses, which is one of my main motivations for this over #41 
This branch maintains API compatibility while providing a generic hook API, similar to what was previously implemented in `handle_DATA()`.  I'm hoping this will solve @Mortal issue in #47 …

Generic hook mechanism

---

README.rst
aiosmtpd/docs/NEWS.rst
aiosmtpd/smtp.py
aiosmtpd/testing/helpers.py
aiosmtpd/tests/test_smtp.py
py34-coverage.ini
unittest.cfg

Test cases for connection problems during readline()
Also, add some much improved debugging options for when the test suite is run
with the -E option.
Update the documentation.
Closes #61

Handle lost connections and EOF during readlines

---

aiosmtpd/docs/cli.rst
setup.py

The $PATH/smtpd command is contested by multiple popular SMTP server implementations: Postfix installs to /usr/lib/postfix/sbin/smtpd on Ubuntu, and opensmtpd installs to /usr/sbin/smtpd. If aiosmtpd tries to install the "smtpd" command upstream, it will probably be changed by most distributions. If we pick a less contested command name, it is more likely to be available uniformly across the distributions that choose to package aiosmtpd.
I came across this while working on documentation. I think this issue would have been more important 5 years ago before pip was standardized as the way to subordinate traditional Linux package distributors, but I think aiosmtpd should still "play nice" and not require setup.py-patching on every downstream. What do you think @warsaw @kozzztik ?

Install as "aiosmtpd" instead of "smtpd"

---

aiosmtpd/docs/smtp.rst
aiosmtpd/smtp.py
aiosmtpd/tests/test_smtp.py

Is 500 the right response to an internal server error (uncaught exception)? The mailing list software I'm running sends `451 Requested action aborted: error in processing` and sends an email to me when an uncaught exception handles. The idea is that the message will be retried for up to five days while I take care of the exception, and since my mailing list only ever talks to the local Postfix server that actually receives email from the Internet, I can even flush the Postfix mail queue immediately after deploying any changes in order to minimize the delay in mail forwarding. With a 5xx response, such messages would instead get lost, so in my case I would definitely run with a 4xx response.
On the other hand, if you're just running aiosmtpd without having any developers to respond …

Allow handle_exception to return a non-500 response

---

aiosmtpd/main.py
appveyor.yml
py34mswin-coverage.ini
py35mswin-coverage.ini
py36mswin-coverage.ini
tox.ini

This PR adds an Appveyor config. When aio-libs/aiosmtpd is created on https://ci.appveyor.com (by the FLUFL), the config will be automatically picked up and tests will start running whenever master is updated.
Currently coverage [fails](https://ci.appveyor.com/project/Mortal/aiosmtpd/build/1.0.6/job/400lst9pqg2bbky7#L615) because this if-branch is always taken in tests:
```python
def eof_received(self):
log.info('%r EOF received', self.session.peer)
self._handler_coroutine.cancel()
if self.transport is not None:                        # pragma: nopy34
return super().eof_received()
```
I can't figure out how to make a test where `eof_received()` is called when `self.transport` is None, but it seems that this is exercised when testing on Linux by the tests in TestStartTLS (discovered by …

Add Appveyor config for testing on Windows

---

aiosmtpd/docs/smtp.rst
aiosmtpd/smtp.py

I just noticed that `Envelope.original_content` is not being set in `Envelope.__init__()`, nor is it documented in the section on the `Envelope` class in the docs.

Document Envelope.original_content in "Envelope" section

---

README.rst

The aiosmtpd tag has just been created on StackOverflow and I've subscribed to notifications whenever new questions are posted in that tag. Add a link under "Project details" along with a suggestion to post questions on StackOverflow.

Add link to StackOverflow tag for aiosmtpd

---

aiosmtpd/handlers.py

Proxy has an incorrect call to `log.error`, and I ran into this error when testing an example that uses Proxy. I remember viewing another aiosmtpd PR that fixes this issue, but I guess that other PR has been deferred post-1.0.

Fix logging error

---

aiosmtpd/docs/handlers.rst

I found a typo while proof-reading #93 -- turns out it was a typo already present in `master`.

Fix typo "essentiall"

---

aiosmtpd/docs/handlers.rst
aiosmtpd/docs/smtp.rst

* It currently sounds like handle_HELO() should return "250 OK". However, it should return the host name. I'm not entirely sure if this is actually required by RFC 5321, but I suggest documenting that it is required by the aiosmtpd handler.
* handle_EHLO() documentation specifies "250 OK" as the return code, however, as I understand it must return "250 HELP".
* SMTP.push() documentation specifies that a string must be UTF-8, but that is nonsense -- it is more correct to say that the string will be encoded as UTF-8.
* Fix a typo in the intro of smtp.rst ("subthead").
[RFC 5321 §4.1.1.1 EHLO and HELO](https://tools.ietf.org/html/rfc5321#section-4.1.1.1): "These commands, and a "250 OK" reply to one of them, confirm that both the SMTP client and the SMTP server are in the initial state, …

handle_HELO/EHLO documentation (+two other doc fixes)

---

aiosmtpd/smtp.py
aiosmtpd/tests/test_smtp.py

As already said in #107 NOOP *SHOULD* accept arguments as stated in RFC 5321 $4.1.1.9.

Fixes NOOP not accepting argument.

---

aiosmtpd/docs/NEWS.rst
aiosmtpd/docs/smtp.rst
aiosmtpd/lmtp.py
aiosmtpd/smtp.py
aiosmtpd/tests/test_lmtp.py
aiosmtpd/tests/test_smtp.py
aiosmtpd/tests/test_starttls.py

Added much better support for the ``HELP``.  There's a new decorator called   ``@syntax()`` which you can use in derived classes to decorate ``smtp_*()``   methods.  These then show up in ``HELP`` responses.  This also fixes  ``HELP`` responses for the ``LMTP`` subclass.
Closes #113 
Supplants #69

Improved help

---

aiosmtpd/controller.py
aiosmtpd/docs/NEWS.rst
aiosmtpd/docs/controller.rst
aiosmtpd/tests/test_smtps.py

This PR adds support for SMTP over SSL/TLS via a custom `SSLContext` supplied to a `Controller` constructor.
This however has a few nits, as the STARTTLS extension is implemented in the `SMTP` protocol class and these two options are orthogonal. It's obviously a wrong use of the library to enable STARTTLS on a `SMTP` instance as well as require SMTP over SSL/TLS via this PRs functionality, however I still think it should be somehow detected and aborted.

Add support for SMTP over SSL/TLS.

---

.travis.yml
aiosmtpd/smtp.py
aiosmtpd/tests/test_smtp.py

Gracefully handle ASCII decoding exceptions

---

aiosmtpd/docs/controller.rst

Note that its use prevents STARTTLS, fix a grammar error and clarify it overall.

Improve Controller ssl_context documentation

---

.travis.yml
aiosmtpd/docs/smtp.rst
aiosmtpd/smtp.py
aiosmtpd/tests/test_smtp.py

Client will now be disconnected after a set period of time, which can be
adjusted.  This prevents one form of resource exhaustion when badly
behaving clients connect and never send any data.
This partially fixes issue #145

Add a timeout feature

---

aiosmtpd/smtp.py
aiosmtpd/tests/test_handlers.py
aiosmtpd/tests/test_smtp.py

Stripping the last \r\n off the DATA command results in the messages
actual size being 2 bytes shorter than the SIZE set in MAIL FROM.
RFC 1870[1]:
>   The message size is defined as the number of octets, including CR-LF
>   pairs, but not the SMTP DATA command's terminating dot or doubled
>   quoting dots, to be transmitted by the SMTP client after receiving
>   reply code 354 to the DATA command.
[1] https://tools.ietf.org/html/rfc1870#section-5

don't strip last CR-LF prior to terminating dot

---

aiosmtpd/smtp.py
release.py
setup.py

This adds a release helper script - basically what I use to upload releases to pypi myself. I don't have any emotional investment in the configuration of this script - it's just me trying to improve that bus factor. If there are improvements then they are very welcome!
Anyway, the idea is that you should be able to create a pypi token and setup a `~/.pypirc`, install necessary packages (e.g. twine), and then you'd be able to run this script any time you needed to release!
In the process of setting up this script, the twine check informed me of the missing field, so I went ahead and fixed that.

Release helpers

---

setup.py

setup.py:
Use the exclude parameter to find_packages() to exclude 'examples' from
the bdist distribution, as the directory is otherwise installed
top-level to the site-packages directory (potentially conflicting with
other packages).
Fixes #181
see above
see above
see above
* name it `<issue_id>.<type>` (e.g. `588.bugfix`)
* if you don't have an `issue_id` change it to the pr id after creating the PR
* ensure type is one of the following:
* `.feature`: Signifying a new feature.
* `.bugfix`: Signifying a bug fix.
* `.doc`: Signifying a documentation improvement.
* `.removal`: Signifying a deprecation or removal of public API.
* `.misc`: A ticket has been closed, but it is not of interest to users.
* Make sure to use full sentences with correct case and punctuation, for example: `Fix issue …

Exclude examples from bdist

---

aiosmtpd/docs/handlers.rst
aiosmtpd/smtp.py
aiosmtpd/tests/test_smtp.py

Change the status code for exceptions to 451 instead of 500.
The user will see delivery retries when their code errors out.
n/a
I am not an experienced Python developer and tox fails on the current master within my environment. I believe I updated all the tests and hope that Travis catches any mistakes.
* name it `<issue_id>.<type>` (e.g. `588.bugfix`)
* if you don't have an `issue_id` change it to the pr id after creating the PR
* ensure type is one of the following:
* `.feature`: Signifying a new feature.
* `.bugfix`: Signifying a bug fix.
* `.doc`: Signifying a documentation improvement.
* `.removal`: Signifying a deprecation or removal of public API.
* `.misc`: A ticket has been closed, but it is not of interest to users.
* Make sure to use full sentences with correct case and …

Default status code on exceptions to 451

---

aiosmtpd/docs/NEWS.rst
aiosmtpd/smtp.py
aiosmtpd/tests/test_smtp.py
aiosmtpd/tests/test_starttls.py

Implement waiting for SSL setup/handshake within STARTTLS handler to be able to catch and handle (log) errors and to avoid session hanging around until timeout in such cases.
Add sessions peer information to some logging output where it was missing.
Better logging of TLS handshake issues and less ressource consumption on such.
Closes #173
* name it `<issue_id>.<type>` (e.g. `588.bugfix`)
* if you don't have an `issue_id` change it to the pr id after creating the PR
* ensure type is one of the following:
* `.feature`: Signifying a new feature.
* `.bugfix`: Signifying a bug fix.
* `.doc`: Signifying a documentation improvement.
* `.removal`: Signifying a deprecation or removal of public API.
* `.misc`: A ticket has been closed, but it is not of interest to users.
* Make sure to use full …

fix tls handshake/error handling

---

aiosmtpd/docs/NEWS.rst
aiosmtpd/docs/handlers.rst
aiosmtpd/smtp.py
aiosmtpd/testing/helpers.py
aiosmtpd/tests/test_smtp.py

When implementing AUTH support, I misunderstood the meaning of `=` (lone equal sign) in [RFC 4954](https://tools.ietf.org/html/rfc4954).
This has been fixed to strictly comply with RFC 4954 and also [RFC 4616](https://tools.ietf.org/html/rfc4616)
This mostly impacts `AUTH PLAIN` which requires a special null-separated struct.
If user (of this library, not an SMTP client) wants to test AUTH PLAIN with null login, then sending `AUTH PLAIN =` or as a response to the challenge will no longer work. This shouldn't be a problem if test is done using Standard Lib's `smtplib.SMTP`, because `smtplib.SMTP.auth_plain` already properly creates the necessary null-separated struct.
None

BUGFIX: RFC4954 behavior for lone "="

---

.gitignore
aiosmtpd/docs/NEWS.rst
aiosmtpd/smtp.py
aiosmtpd/testing/helpers.py
aiosmtpd/tests/test_smtp.py

Sanitize command line before logging.
This prevents leakage of sensitive information.
Only if user parses the log output.
If user _absolutely_ needs to capture the SMTP credentials, user can:
1. Override the `auth_*` methods and/or set `log_client_response=True` on calls to `SMTP._auth_interact()` (for custom, non-built-in AUTH mechanisms), or
2. Perform the logging within the `auth_callback` function
Closes #233 
[1] [12.1 is being EOL-ed](https://www.freebsd.org/security/index.html#sup). Side benefit: Since I decided to just wipe my VM and reinstall from scratch, lo and behold! Now all `pypy3` tests work! And the icing on the cake is that the whole tox suite runs much faster than before!

Hide password in logs

---

.github/workflows/unit-testing-and-coverage.yml
aiosmtpd/__init__.py
aiosmtpd/controller.py
aiosmtpd/docs/NEWS.rst
aiosmtpd/docs/controller.rst
aiosmtpd/smtp.py
aiosmtpd/tests/test_server.py
release.py

Previously, `Controller._testconn()`, on Linux, will raise an error if `self.hostname=""`. This is due to `socket.create_connection()` not accepting `""` as hostname parameter. (Totally no problem in Windows)
In addition, `Controller.run()` wraps _all_ exceptions generated by `_testconn()` so this particular error is not seen, leading to hard times during troubleshooting.
Also, even if `hostname` not specified, `Controller` defaults to `"::1"`, which is not available on systems with IPv6 disabled.
Finally, previously `ready_timeout` is used only to wait, with no action taken if it's reached.
So, the changes:
* Now uses a smarter way to determine 'default localhost' address by attempting `::1`, and if that fails, `127.0.0.1`
* `ready_timeout` actually acts if timeout is breached
* Only …

Fix Controller Bug on hostname="" or IPv6 not available

---

DESCRIPTION.rst
README.rst
aiosmtpd/__init__.py
aiosmtpd/controller.py
aiosmtpd/docs/NEWS.rst
aiosmtpd/docs/controller.rst
aiosmtpd/tests/test_server.py
housekeep.py
release.py
setup.cfg
tox.ini

Add `errno.EAFNOSUPPORT` to IPv6 detection.
Also:
* Update test cases
* Update `controller.rst`
* Update `README.rst` -- now contains ID of Signing Key for PyPI and GH Releases
* Update PyPI Long Description -- now contains ID of Signing Key for PyPI and GH Releases
* Update `housekeep.py`
None.
Closes #244

Fix ipv6 detection

---

.gitignore
README.rst
aiosmtpd/__init__.py
aiosmtpd/docs/NEWS.rst
aiosmtpd/tests/test_main.py
aiosmtpd/tests/test_proxyprotocol.py
housekeep.py
pyproject.toml
setup.cfg
tox.ini

* Introduce changes that enables the "pypy3" testenv to run on Windows.
* Add the "platform" attribute to the "static" testenv that unselects the testenv if run on `sys.platform == "win32"`
* Introduce `OSError` catching for [MacOS race condition](http://erickt.github.io/blog/2014/11/19/adventures-in-debugging-a-potential-osx-kernel-bug/) that causes test cases to intermittently fail on MacOS
* Updates to `README.rst`
None. This affects testing (with tox) only.
None

Fix "pypy3" testenv on Windows, Fix MacOS flakeyness

---

aiosmtpd/__init__.py
aiosmtpd/docs/NEWS.rst
aiosmtpd/docs/smtp.rst
aiosmtpd/smtp.py
aiosmtpd/tests/test_smtp.py

Main change is the relaxing of the "email address local part length": Previously it was capped at 64 octets, now it is not limited, but with an option to activate the limiting.
This "unlimited local part length" feature is apparently needed by some other libraries that rely on aiosmtpd.
User can no longer rely on aiosmtpd automatically rejecting email addresses whose "local part" is longer than 64 octets; users that _need_ such behavior can still get the same behavior by setting the `local_part_limit` attribute of the instantiated SMTP class (e.g., changing the `Controller.smtpd.local_part_limit` value).
Closes #257

Relax limit for local part length

---

aiosmtpd/__init__.py
aiosmtpd/controller.py
aiosmtpd/docs/NEWS.rst
aiosmtpd/docs/controller.rst
aiosmtpd/tests/test_proxyprotocol.py
aiosmtpd/tests/test_server.py

`ready_timeout`, as the name implies, is the maximum time `BaseController` will wait for 3 events to have happened: (1) asyncio loop starting, (2) asyncio creating the server listener, and (3) server responding to initial (trigger) connection.
With all the features that we have been adding since 1.2.2, the original default of `1.0` is getting more and more "marginal", so to speak. A busy system can now easily push the (1-2-3) events above to beyond 1.0.
Since `ready_timeout` is a timeout limit instead of a sleep delay, increasing its default value should not slow down the Controller startup process; rather, it will give (much) additional time for startup to complete.
In parallel to this, I extended the error messages for the TimeoutError's related to `ready_timeout`, to help users to tune …

Increase default ready_timeout to 5.0

---

aiosmtpd/__init__.py
aiosmtpd/docs/NEWS.rst
aiosmtpd/smtp.py
aiosmtpd/testing/statuscodes.py
aiosmtpd/tests/test_smtp.py
pyproject.toml

It has come to my attention that [one particular line of logging](https://github.com/aio-libs/aiosmtpd/blob/9c2a13eac52c6c293335b45c7c644ebc794a6905/aiosmtpd/smtp.py#L925) potentially leaks sensitive information (password).
This PR overrides the `__repr__` and `__str__` methods of `AuthResult` and `LoginPassword` to prevent this leakage. 
This impacts Users that rely on the repr() and str() of AuthResult and LoginPassword (why??), directly or indirectly (via logs).
The impact should be deemed acceptable compared to the potential sensitive information leakage.
None

Sanitize AUTH Logging

---

.github/workflows/unit-testing-and-coverage.yml
aiosmtpd/tests/test_handlers.py
aiosmtpd/tests/test_smtp.py
tox.ini

* One of the test cases are testing a bug in Python stdlib that was
fixed in 3.10 and backported to 3.9 and 3.8. This updates the
version check to make it pass on all supported versions.
* Bump dependency on actions/setup-python@v4
* Add dependency on 'py' to fix the non-declared dependency in
pytest-sugar.
* Temporarily break the dependency between unit tests and QA tests
so we can make progress on fixing the unit tests and QA in parallel.
No.
Partially related to #277 

fix: Fix the testcase that isn't applicable to all python version.

---

.github/workflows/unit-testing-and-coverage.yml
aiosmtpd/controller.py
aiosmtpd/tests/test_server.py
aiosmtpd/tests/test_smtp.py
setup.cfg

Fix an issue with the use of SSL server context in cilents to call
into the server for lazy loading of init logic in server. This commit
adds a helper function that translates server context to client context
in the right places.
Full support for 3.10 depends on #307 and possibly #308
* This should add support for Python 3.10
Fixes #277 

feat: Add support for Python 3.10.

---

tox.ini

Run type checking during the tox qa env so that we can test
locally for any typing related errors instead of manually
installing and running pytype.
Developers will now also see typing related failures when
running qa tox env locally.
Fixes #310 

tests: Run pytype as a part of tox qa testenv

---

.github/workflows/unit-testing-and-coverage.yml
aiosmtpd/smtp.py
aiosmtpd/tests/test_smtp.py
aiosmtpd/tests/test_starttls.py
setup.cfg
tox.ini

Changes:
- ci: Enable 3.11 in CI
- use b64 encoded "=" commands otherwise we get decoding errors. 
- fixes to use set_protocol() instead of setting an internal property
as we no longer support 3.5.
Add support for Python 3.11
No.

feat: Add support for Python 3.11

---

.github/workflows/unit-testing-and-coverage.yml
tox.ini

Speedup of #323 + many modernizations, such as:
* Add pypy3.8
* Exclude pypy3.6 on Windows (no longer available)
* Remove 3.6 (end of life already -- let it rest in peace)
* Actions use Node 16
And a workaround:
* Skip code coverage when running on pypy3.8 (not sure why it doesn't hit 100%)
Now all steps are green and runs in acceptable time, as can be seen in [CI #451](https://github.com/aio-libs/aiosmtpd/actions/runs/3696059951)
If merged this closes #316

Enhance GitHUB CI Workflow

---

aiosmtpd/docs/handlers.rst

Looks like a copy/paste error from `handle_MAIL`
Update the docs.
No
None

Update to docs for handle_RCPT

---

setup.cfg

Some files have runtime dependency on setuptools because of importing `pkg_resources` module. In Fedora, we build the package using setuptools, but we ship it to users potentially without it. I suggest explicitly list this requirement. 
No

Explicitly require setuptools, tests/test_smtps.py and tests/test_starttls.py imports pkg_resources

---

aiosmtpd/__init__.py
aiosmtpd/docs/NEWS.rst
tox.ini

Bumping version to 1.4.3 which includes:
* Updates to NEWS
* Updates to DESCRIPTION and README
* Integrates updates since 1.4.3rc2. Notable ones:
* Compatibility with `uvloop`
* Expanded tox environments
Shouldn't be any.
Closes #322

Bump 1.4.3 final (for release!)

---

DESCRIPTION.rst
README.rst

As mentioned [here](https://github.com/aio-libs/aiohttp/discussions/7140) and [here](https://github.com/aio-libs/aiohttp/issues/7141), it's clear that the Discourse dicussion group at `aio-libs.discourse.group` is dead.
There's even already a [**merged PR**](https://github.com/aio-libs/aiohttp/pull/7144) where the Discourse link is removed from `aiohttp`.
When they click the link they will now go to GH Discussions.
Not issue, but Discussion #340

Remove Discourse, replace with GH Discussions

---

aiosmtpd/docs/controller.rst
aiosmtpd/tests/test_server.py

Replace call to `.setDaemon()` to direct setting of `.daemon` attribute, [as described in the documentation](https://docs.python.org/3/library/threading.html#threading.Thread.setDaemon).
None.
None.

setDaemon() is deprecated, set the daemon attrib directly instead

---

tox.ini

I had just managed to b0rk my cloned repo _completely_ when I specify tox to run `pypy38-nocov`.
That is due to `envdir` not specified explicitly so `tox` decides to 'clean up' my cloned repo and build its environment _right there_.
After recloning, I found out that tox now will recreate environment if the envname changes, so `py37-nocov` and `py37-cov` (for instance) can no longer share same packages. Meaning that previous "common deps" list is useless.
So I decided to just specify a specific envdir for all envname (i.e., combination of Pyton version + what test), and use conditionals on the deps installation.
Not really. However developers might find that hard disk usage balloons. Use `housekeep.py superclean`, it's there for a reason 😉
None

Change tox behavior

---

.github/workflows/unit-testing-and-coverage.yml
README.rst

No longer test with PyPy3.6.
PyPy3.6 has been EOL-ed for quite some time, and not available on non-Ubuntu runners anyways.
None.
None

Drop testing for PyPy3.6, add PyPy3.9

---

aiosmtpd/__init__.py
aiosmtpd/docs/NEWS.rst
aiosmtpd/docs/controller.rst
aiosmtpd/handlers.py
aiosmtpd/main.py
aiosmtpd/smtp.py
aiosmtpd/tests/conftest.py
aiosmtpd/tests/test_misc.py
examples/authenticated_relayer/server.py
examples/basic/server.py
pyproject.toml

Implement workaround due to the deprecation in ***behavior*** of asyncio.get_event_loop() (which will outright result in error with Python 3.12)
This change of behavior first appeared in Python 3.10: https://docs.python.org/3.10/library/asyncio-eventloop.html#asyncio.get_event_loop
And there has been some discussion on this, among others:
* https://github.com/python/cpython/issues/83710
* https://github.com/python/cpython/issues/93453
* https://github.com/python/cpython/pull/98440
Should be minimal.
* If user creates their own event loop and feeds that to aiosmtpd, then nothing will be changed
* If user does not create their own event loop and let aiosmtpd generates one for them, then the behavior totally depends on how `get_event_loop_policy()` was in effect at time of instantiation.
* …

Workaround for asyncio.get_event_loop() deprecation

---

aiosmtpd/__init__.py
aiosmtpd/docs/NEWS.rst
aiosmtpd/qa/test_0packaging.py
release.py

Makes `release.py` block release process if git is unclean, preventing snippets that one forgot to shelf from tainting the release sdist & wheel
None. This is purely a packaging issue.
Prevents #365 from happening again.

Block release if git unclean

---

aiosmtpd/smtp.py

Removed NEWLINE global variable
Removed unused global NEWLINE variable.
No
No

Remove unused NEWLINE global

---

aiosmtpd/docs/NEWS.rst
aiosmtpd/smtp.py

When a STARTTLS command is not the last one in a pipeline, extra unencrypted commands may treated as part of the encrypted communication, effectively allowing to bypass the `ALLOWED_BEFORE_STARTTLS` list used when `require_starttls=True`.  This PR adds a buffer flush to ensure it does not happen.
No behaviour change.  Documentation reflects the changes already.
None.

starttls: Clear unencrypted commands from buffer

---

pytest.ini
requirements.txt

Currently, `tox` fails because of `pytest-asyncio` missing in dependencies in `tox.ini`:
```
$ tox -e py311-cov --recreate
...
INTERNALERROR> pytest.PytestConfigWarning: Unknown config option: asyncio_mode
```
One way is to add it there, however it looks like it is not necessary at
all:
* After removing all the traces tests pass without raising  `PytestUnhandledCoroutineWarning`.
* Introduction of `pytest-asyncio` in https://github.com/aio-libs/aiosmtpd/pull/395 was not justified.
Apparently, it was added, because it was present in other aio-libs packages.
* The output of `rg 'async def ' aiosmtpd/tests aiosmtpd/testing` shows no instances of tests.
No changes for the user.
* You may create subsections to group the …

Remove `pytest-asyncio` traces

---

aiosmtpd/tests/conftest.py
requirements-dev.txt

migrate config_test from pkg_resources to importlib_resources
pkg_resources is now throwing a deprecation warning
this is only used to get the cert filenames
[](https://setuptools.pypa.io/en/latest/pkg_resources.html)
[](https://importlib-resources.readthedocs.io/en/latest/migration.html)
no, test infra only

migrate config_test from pkg_resources to importlib_resources
